# Generated by Django 4.2 on 2023-05-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(choices=[('Nimat', 'Niamtallah Akinyele'), ('akinwale', ' '), ('olawale', 'IB AK')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='GodsChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=20)),
                ('column2', models.IntegerField()),
                ('column3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('column4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
    ]
