# Generated by Django 4.2 on 2023-05-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_options_alter_article_author_godschild'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GodsChild',
        ),
    ]
